apiVersion: v1
kind: Pod
metadata:
  name: democpu
spec:
   containers:
     - name: demo
       image: alpine
       resources:
          requests: 
             cpu: 20m
             memory: 20M
          limits:
              cpu: 50m
              memory: 50M
