apiVersion: v1
kind: Pod
metadata:
  name: webpod
  namespace: default
  labels:
    env: dev
spec:
  containers:
    - name: tomcat
      image: tomcat
      ports:
      - name: http
        containerPort: 8080